//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrudOperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_T_EMPLOYEE
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public byte Age { get; set; }
        public decimal Salary { get; set; }
        public string ManagerName { get; set; }
        public string EmpStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifideBy { get; set; }
    }
}
